# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f934ec5f9471ccb90a10267cd7b9a2e549e9ae90da73f7f9b3b385620bb282e3008de2910536026bb44f79a245f6eb2427ae2347188ddfc4866a0f2ba0679438

test:
  secret_key_base: 2532a47e6d181dc2fcb3a5accaf57494c4054c391fc270537107b6b1876b103c757b196dff2a1a8abe04f6e2fd90bc5658421f764136012c2cd75110523cd7d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
